name: get_cli
version: 5.0.0-release-candidate-4
homepage: https://github.com/jonataslaw/get_cli
description: Official CLI for GetX™ framework to build Flutter and Server
  Applications easily
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  #  archive: ^3.1.2
  ansicolor: ">=2.0.1 <3.0.0"
  collection: ">=1.15.0 <2.0.0"
  dart_style: ">=2.0.1 <3.0.0"
  dcli: ^4.0.5
  get: ^5.0.0-release-candidate-4
  http: ">=0.13.4 <2.0.0"
  intl: ">=0.17.0 <1.0.0"
  meta: ">=1.7.0 <2.0.0"
  path: ">=1.8.0  <2.0.0"
  process_run: ">=0.12.2 <1.0.0"
  pubspec: ">=2.0.1 <3.0.0"
  recase: ">=4.0.0 <5.0.0"
  version: ">=2.0.0 <4.0.0"
  yaml: ">=3.1.0 <4.0.0"
dependency_overrides:
  meta: ^1.15.0  # 与 runtime_native_semaphores 的要求匹配
  runtime_native_semaphores: ^1.0.0-beta.6  # 与 dcli 的要求匹配
dev_dependencies:
  lints: ^2.0.0
  test: ^1.5.0

executables:
  get: get
  getx: get
